development:
  adapter: postgresql
  encoding: unicode
  database: tht_development
  pool: 5
  username: dbtiger
  password: pypy

test:
  adapter: postgresql
  encoding: unicode
  database: tht_test
  pool: 5
  username: dbtiger
  password: pypy