development:
  adapter: postgresql
  encoding: unicode
  database: tht_development
  host: localhost
  pool: 5
  username: manaswi
  password: pepper

test:
  adapter: postgresql
  encoding: unicode
  database: tht_test
  pool: 5
  username: manaswi
  password: pepper